name: info_popup
description: The simple way to show the user some information on your selected widget.
version: 3.0.0
repository: https://github.com/salihcanbinboga/info_popup

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example:
    path: example
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
